# Generated by Django 5.1.2 on 2024-10-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAutomatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
                ('categoria', models.CharField(choices=[('AUTOMATICO', 'Automático'), ('MANUAL', 'Manual')], max_length=10)),
                ('voltaje', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
                ('categoria', models.CharField(choices=[('AUTOMATICO', 'Automático'), ('MANUAL', 'Manual')], max_length=10)),
                ('material', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
