# Generated by Django 5.1.2 on 2024-10-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoautomatico',
            name='categoria',
            field=models.CharField(choices=[('AUTOMATICO', 'Automático'), ('MANUAL', 'Manual')], max_length=12),
        ),
        migrations.AlterField(
            model_name='productomanual',
            name='categoria',
            field=models.CharField(choices=[('AUTOMATICO', 'Automático'), ('MANUAL', 'Manual')], max_length=12),
        ),
    ]
