# Generated by Django 5.1.2 on 2024-10-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0003_producto_delete_productoautomatico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
